const std = @import("std");

// zig port of "MKlib_gen.sh"

pub fn main(init: std.process.Init, arg0: []const u8, args: []const []const u8) !void {
    _ = arg0;
    const io = init.io;
    const cwd = std.Io.Dir.cwd();

    std.debug.assert(args.len >= 3);
    const outpath = args[0];
    const curses_h = args[1];
    const awk = args[2];

    _ = curses_h;
    _ = awk;

    const outfile = try cwd.createFile(io, outpath, .{});
    defer outfile.close(io);

    var outbuf: [4096]u8 = undefined;
    var output = outfile.writer(io, &outbuf);
    defer output.interface.flush() catch unreachable;
    const writer = &output.interface;

    try writer.print(
        \\/* This file was generated by {s} */
        \\
    , .{@src().file});

    // TODO: implement MKlib_gen.sh
    // original shell call:
    // ./base/MKlib_gen.sh "$CC" "mawk" generated <../include/curses.h
    try writer.writeAll(
        \\/*
        \\ * DO NOT EDIT THIS FILE BY HAND!
        \\ *
        \\ * This is a file of trivial functions generated from macro
        \\ * definitions in curses.h to satisfy the XSI Curses requirement
        \\ * that every macro also exist as a callable function.
        \\ *
        \\ * It will never be linked unless you call one of the entry
        \\ * points with its normal macro definition disabled. In that
        \\ * case, if you have no shared libraries, it will indirectly
        \\ * pull most of the rest of the library into your link image.
        \\*/
        \\
        \\#error "lib_gen.c not implemented"
        \\#error '/base/MKlib_gen.sh "$CC" "mawk" generated <../include/curses.h'
        \\
    );
}
