const std = @import("std");
const Capability = @import("Capability.zig");

pub fn main(init: std.process.Init, arg0: []const u8, args: []const []const u8) !void {
    _ = arg0;
    const io = init.io;
    const cwd = std.Io.Dir.cwd();

    std.debug.assert(args.len >= 1);
    const outpath = args[0];
    const inpaths = args[1..];

    const outfile = try cwd.createFile(io, outpath, .{});
    defer outfile.close(io);

    var outbuf: [4096]u8 = undefined;
    var output = outfile.writer(io, &outbuf);
    defer output.interface.flush() catch unreachable;
    const writer = &output.interface;

    var hashsize: usize = 0;

    for (inpaths) |file_path| {
        const fd = try cwd.openFile(io, file_path, .{});
        defer fd.close(io);
        var read_buf: [4096]u8 = undefined;
        var reader = fd.reader(io, &read_buf);

        line: while (try reader.interface.takeDelimiter('\n')) |line| {
            if (Capability.should_skip_line(line)) continue :line;
            hashsize += 1;
        }
    }

    try writer.print(
        \\/* This file was generated by {s}
        \\ * hashsize.h -- hash and token table constants
        \\*/
        \\
        \\#define CAPTABSIZE    {d}
        \\#define HASHTABSIZE   ({d} * 2)
        \\
    , .{ @src().file, hashsize, hashsize });
}
