const std = @import("std");
const Capability = @import("Capability.zig");

// MKkeydefs.sh

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    const cwd = std.Io.Dir.cwd();

    std.debug.assert(args.len >= 3);
    const outpath = args[1];
    const inpaths = args[2..];

    const outfile = try cwd.createFile(io, outpath, .{});
    defer outfile.close(io);

    var outbuf: [4096]u8 = undefined;
    var output = outfile.writer(io, &outbuf);
    defer output.interface.flush() catch unreachable;
    const writer = &output.interface;

    {
        try writer.print(
            \\/*
            \\* These definitions were generated by {s}
        , .{@src().file});

        for (inpaths) |inpath| {
            try writer.writeAll(" ");
            try writer.writeAll(std.fs.path.basename(inpath));
        }
        try writer.writeAll("\n*/\n");
    }

    var caps: Capability.List = .empty;
    defer caps.deinit(gpa);

    for (inpaths) |inpath| {
        const infile = try cwd.readFileAlloc(io, inpath, arena, .unlimited);

        try caps.parseFile(gpa, infile);
    }
    caps.sortBy_termcap_value();

    var cap_max: u32 = 0;
    for (caps.array.items) |cap| {
        cap_max = @max(cap_max, cap.termcap_value orelse continue);
        try writer.print("{f}\n", .{cap});
    }

    {
        try writer.print(
            \\
            \\#ifdef NCURSES_EXT_FUNCS
            \\#define KEY_RESIZE{s}{:0>4}{s}/* Terminal resize event */
            \\#endif
            \\
            \\#define KEY_MAX{s}0777{s}/* Maximum key value is {:0>4} */
            \\/*
            \\* The above definitions were generated by {s} 
        ,
            .{
                "\t",
                cap_max + 1,
                "\t\t",
                "\t\t",
                "\t\t",
                cap_max + 1,
                std.fs.path.basename(args[0]),
            },
        );

        for (inpaths) |inpath| {
            try writer.writeAll(" ");
            try writer.writeAll(std.fs.path.basename(inpath));
        }
        try writer.print("\n* cap_count: {}\n*/\n", .{caps.array.items.len});
    }
}
