const std = @import("std");

pub fn main(init: std.process.Init) !void {
    // const gpa = init.gpa;
    const io = init.io;
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    const cwd = std.Io.Dir.cwd();

    std.debug.assert(args.len >= 2);
    const outpath = args[1];
    const inpaths = args[2..];

    const outfile = try cwd.createFile(io, outpath, .{});
    defer outfile.close(io);

    var outbuf: [4096]u8 = undefined;
    var output = outfile.writer(io, &outbuf);
    defer output.interface.flush() catch unreachable;
    const writer = &output.interface;

    var hashsize: usize = 0;

    for (inpaths) |file_path| {
        const fd = try cwd.openFile(io, file_path, .{});
        defer fd.close(io);
        var read_buf: [4096]u8 = undefined;
        var reader = fd.reader(io, &read_buf);

        outer: while (try reader.interface.takeDelimiter('\n')) |line| {
            if (line.len == 0) continue;
            inline for (&.{
                "#",
                " ",
                "capalias",
                "infoalias",
                "userdef",
                "used_by",
            }) |skip_str| {
                if (std.mem.startsWith(u8, line, skip_str)) continue :outer;
            }
            hashsize += 1;
        }
    }

    try writer.print(
        \\/* This file was generated by {s}
        \\ * hashsize.h -- hash and token table constants
        \\*/
        \\
        \\#define CAPTABSIZE    {d}
        \\#define HASHTABSIZE   ({d} * 2)
        \\
    , .{ @src().file, hashsize, hashsize });
}
