const std = @import("std");

pub fn main(init: std.process.Init) !void {
    // const gpa = init.gpa;
    const io = init.io;
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    const cwd = std.Io.Dir.cwd();

    std.debug.assert(args.len >= 4);
    const outpath = args[1];
    const curses_h = args[2];
    const awk = args[3];

    _ = curses_h;
    _ = awk;

    const outfile = try cwd.createFile(io, outpath, .{});
    defer outfile.close(io);

    var outbuf: [4096]u8 = undefined;
    var output = outfile.writer(io, &outbuf);
    defer output.interface.flush() catch unreachable;
    const writer = &output.interface;

    try writer.print(
        \\/* This file was generated by {s} */
        \\
    , .{@src().file});

    // TODO: implement MKlib_gen.sh
    // original shell call:
    // ./base/MKlib_gen.sh "$CC" "mawk" generated <../include/curses.h
    try writer.writeAll(
        \\/*
        \\ * DO NOT EDIT THIS FILE BY HAND!
        \\ *
        \\ * This is a file of trivial functions generated from macro
        \\ * definitions in curses.h to satisfy the XSI Curses requirement
        \\ * that every macro also exist as a callable function.
        \\ *
        \\ * It will never be linked unless you call one of the entry
        \\ * points with its normal macro definition disabled. In that
        \\ * case, if you have no shared libraries, it will indirectly
        \\ * pull most of the rest of the library into your link image.
        \\*/
        \\
        \\#error "lib_gen.c not implemented"
        \\#error '/base/MKlib_gen.sh "$CC" "mawk" generated <../include/curses.h'
        \\
    );
}
