const std = @import("std");

const Param = struct {
    type_str: []const u8,
    name: []const u8,
};

pub fn main(init: std.process.Init) !void {
    const io = init.io;
    const gpa = init.gpa;
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    const cwd = std.Io.Dir.cwd();

    std.debug.assert(args.len == 5);
    const outpath = args[1];
    _ = args[2]; // zig exe
    const curses_h_path = args[3];
    const use_marker = args[4];
    // const use_marker = try std.fmt.allocPrint(arena, "{s}:", .{
    //     args[4],
    // });

    // Read curses.h
    const curses_h_file = try cwd.openFile(io, curses_h_path, .{});
    defer curses_h_file.close(io);

    var read_buf: [16384]u8 = undefined;
    var reader = curses_h_file.reader(io, &read_buf);

    // Create output file
    const outfile = try cwd.createFile(io, outpath, .{});
    defer outfile.close(io);

    var write_buf: [8192]u8 = undefined;
    var writer = outfile.writer(io, &write_buf);
    const w = &writer.interface;

    // Write header
    try w.print("/* This file was generated by {s} */\n\n", .{@src().file});
    try w.writeAll(
        \\/*
        \\ * DO NOT EDIT THIS FILE BY HAND!
        \\ *
        \\ * This is a file of trivial functions generated from macro
        \\ * definitions in curses.h to satisfy the XSI Curses requirement
        \\ * that every macro also exist as a callable function.
        \\ *
        \\ * It will never be linked unless you call one of the entry
        \\ * points with its normal macro definition disabled. In that
        \\ * case, if you have no shared libraries, it will indirectly
        \\ * pull most of the rest of the library into your link image.
        \\ */
        \\#define NCURSES_ATTR_T int
        \\#include <ncurses_cfg.h>
        \\
        \\#undef NCURSES_NOMACROS /* _this_ file uses macros */
        \\#define NCURSES_NOMACROS 1
        \\
        \\#include <curses.priv.h>
        \\
    );

    // Parse curses.h for "extern" declarations with "generated" marker
    // var current_line = std.ArrayList(u8).empty;
    // defer current_line.deinit(gpa);

    while (try reader.interface.takeDelimiter('\n')) |line| {
        const trimmed = std.mem.trim(u8, line, " \t\r");

        // Check if this line mentions "generated:" or "implemented:"
        if (std.mem.containsAtLeast(u8, trimmed, 1, use_marker)) {
            // Add this line to current_line
            // if (current_line.items.len > 0) {
            //     try current_line.append(gpa, ' ');
            // }
            // try current_line.appendSlice(gpa, trimmed);

            // Now we have a complete declaration (might be multi-line)
            const full_decl = std.mem.trim(u8, line, " \t\r");

            if (std.mem.startsWith(u8, full_decl, "extern")) {
                // Extract the marker (e.g., "generated:LIB_FEATURE")
                if (std.mem.indexOf(u8, full_decl, use_marker)) |marker_start| {
                    // Extract function signature (between "extern" and "generated")
                    const sig_start = "extern".len;
                    var sig = std.mem.trim(u8, full_decl[sig_start..marker_start], " \t\r");

                    // Remove trailing semicolon
                    if (std.mem.endsWith(u8, sig, ";")) {
                        sig = sig[0 .. sig.len - 1];
                    }
                    sig = std.mem.trim(u8, sig, " \t");
                    std.log.info("sig: '{s}'", .{sig});

                    try generateWrapperFunctionFromSignature(w, gpa, sig);
                }
            }

            // current_line.clearRetainingCapacity();
            // } else if (std.mem.startsWith(u8, trimmed, "extern")) {
            //     // Start of a potential multi-line declaration
            //     if (current_line.items.len > 0) {
            //         current_line.clearRetainingCapacity();
            //     }
            //     try current_line.appendSlice(gpa, trimmed);
            // } else if (current_line.items.len > 0) {
            //     // Continue accumulating this multi-line declaration
            //     try current_line.append(gpa, ' ');
            //     try current_line.appendSlice(gpa, trimmed);
        }
    }

    try writer.interface.flush();
}
fn generateWrapperFunctionFromSignature(writer: anytype, allocator: std.mem.Allocator, signature: []const u8) !void {
    // Find opening parenthesis
    const paren_start = std.mem.lastIndexOf(u8, signature, "(") orelse return;
    const paren_end = std.mem.lastIndexOf(u8, signature, ")") orelse return;

    // Extract return type and function name
    const before_paren = std.mem.trim(u8, signature[0..paren_start], " \t");

    // Find the function name (last word before paren)
    var func_name_idx = before_paren.len;
    while (func_name_idx > 0 and (std.ascii.isAlphanumeric(before_paren[func_name_idx - 1]) or before_paren[func_name_idx - 1] == '_')) {
        func_name_idx -= 1;
    }
    const func_name = before_paren[func_name_idx..];

    // Return type is everything before the function name
    const return_type = std.mem.trim(u8, before_paren[0..func_name_idx], " \t");

    // Parse parameters
    const params_str = std.mem.trim(u8, signature[paren_start + 1 .. paren_end], " \t");

    var params = std.ArrayList(Param).empty;
    defer {
        for (params.items) |p| {
            allocator.free(p.type_str);
            allocator.free(p.name);
        }
        params.deinit(allocator);
    }

    if (!std.mem.eql(u8, params_str, "void") and params_str.len > 0) {
        var param_list = std.mem.tokenizeSequence(u8, params_str, ",");
        while (param_list.next()) |param| {
            const trimmed_param = std.mem.trim(u8, param, " \t");
            if (trimmed_param.len == 0) continue;

            // Parse individual parameter (type name)
            var param_idx = trimmed_param.len;
            while (param_idx > 0 and (std.ascii.isAlphanumeric(trimmed_param[param_idx - 1]) or trimmed_param[param_idx - 1] == '_')) {
                param_idx -= 1;
            }
            const p_name = std.mem.trim(u8, trimmed_param[param_idx..], " \t");
            const p_type = std.mem.trim(u8, trimmed_param[0..param_idx], " \t");

            if (p_name.len > 0 and p_type.len > 0) {
                try params.append(allocator, .{
                    .type_str = try allocator.dupe(u8, p_type),
                    .name = try allocator.dupe(u8, p_name),
                });
            }
        }
    }

    std.log.info("return: '{s}'", .{return_type});
    std.log.info("func: '{s}'", .{func_name});
    // Output function wrapper
    try writer.print("{s} {s} ({s})\n", .{
        return_type,
        func_name,
        signature[paren_start..],
    });

    try writer.writeAll("{\n");

    // Generate trace call
    try writer.writeAll("\tT((T_CALLED(\"");
    try writer.writeAll(func_name);
    try writer.writeAll("(");

    for (params.items, 0..) |p, i| {
        if (i > 0) try writer.writeAll(",");
        try writer.writeAll("%");
        if (std.mem.containsAtLeast(u8, p.type_str, 1, "*")) {
            try writer.writeAll("p");
        } else if (std.mem.containsAtLeast(u8, p.type_str, 1, "chtype")) {
            try writer.writeAll("s");
        } else if (std.mem.containsAtLeast(u8, p.type_str, 1, "int")) {
            try writer.writeAll("d");
        } else {
            try writer.writeAll("s");
        }
    }

    try writer.writeAll(")\")");

    for (params.items, 0..) |p, i| {
        try writer.writeAll(", ");
        if (std.mem.containsAtLeast(u8, p.type_str, 1, "chtype")) {
            try writer.print("_tracechtype2({d},{s})", .{ i, p.name });
        } else if (std.mem.containsAtLeast(u8, p.type_str, 1, "*")) {
            try writer.print("(const void *){s}", .{p.name});
        } else {
            try writer.writeAll(p.name);
        }
    }

    try writer.writeAll("));\n");

    // Generate return statement
    const wrapper_func = if (std.mem.startsWith(u8, func_name, "w"))
        func_name
    else if (std.mem.startsWith(u8, func_name, "add"))
        "wadd"
    else if (std.mem.startsWith(u8, func_name, "attr"))
        "wattr"
    else if (std.mem.startsWith(u8, func_name, "bkgd"))
        "wbkgd"
    else if (std.mem.startsWith(u8, func_name, "border"))
        "wborder"
    else if (std.mem.startsWith(u8, func_name, "box"))
        "wbox"
    else
        "w";

    if (std.mem.eql(u8, return_type, "void")) {
        try writer.print("\t{s}(", .{wrapper_func});
    } else {
        try writer.print("\treturnCode({s}(", .{wrapper_func});
    }

    try writer.writeAll("stdscr");
    for (params.items) |p| {
        try writer.print(",({s})", .{p.name});
    }

    if (std.mem.eql(u8, return_type, "void")) {
        try writer.writeAll(");\n\treturnVoid;\n");
    } else {
        try writer.writeAll("));\n");
    }

    try writer.writeAll("}\n");
}

fn parseFunctionSignature(allocator: std.mem.Allocator, signature: []const u8) !?FuncInfo {
    // This function is no longer used - parseWrapperFunctionFromSignature handles everything inline
    _ = allocator;
    _ = signature;
    return null;
}

const FuncInfo = struct {};

fn generateWrapperFunction(writer: anytype, func: FuncInfo) !void {
    _ = writer;
    _ = func;
}

fn getWrapperFunc(func_name: []const u8) []const u8 {
    _ = func_name;
    return "";
}

fn generateTraceCall(writer: anytype, func: FuncInfo) !void {
    _ = writer;
    _ = func;
}

fn generateReturnStatement(writer: anytype, func: FuncInfo, wrapper: []const u8) !void {
    _ = writer;
    _ = func;
    _ = wrapper;
}
