const std = @import("std");

pub fn main(init: std.process.Init) !void {
    // const gpa = init.gpa;
    const io = init.io;
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    const cwd = std.Io.Dir.cwd();

    std.debug.assert(args.len >= 2);
    const outpath = args[1];
    // const inpaths = args[2..];

    const outfile = try cwd.createFile(io, outpath, .{});
    defer outfile.close(io);

    var outbuf: [4096]u8 = undefined;
    var output = outfile.writer(io, &outbuf);
    defer output.interface.flush() catch unreachable;
    const writer = &output.interface;

    try writer.print(
        \\/* This file was generated by {s} */
        \\
    , .{@src().file});

    // TODO: this actually needs to be conditional maybe?
    // original shell call:
    // ./ncurses/tinfo/MKfallback.sh $(TERMINFO) $(TERMINFO_SRC) "$(TIC_PATH)" "$(INFOCMP_PATH)" $(FALLBACK_LIST)
    try writer.writeAll(
        \\/*
        \\ * DO NOT EDIT THIS FILE BY HAND!
        \\*/
        \\
        \\#include <curses.priv.h>
        \\
        \\NCURSES_EXPORT(const TERMTYPE2 *)
        \\_nc_fallback2 (const char *name GCC_UNUSED)
        \\{
        \\    /* the fallback list is empty */
        \\    return((const TERMTYPE2 *)0);
        \\}
        \\
        \\#if NCURSES_EXT_NUMBERS
        \\#undef _nc_fallback
        \\
        \\/*
        \\ * This entrypoint is used by tack 1.07
        \\ */
        \\NCURSES_EXPORT(const TERMTYPE *)
        \\_nc_fallback (const char *name)
        \\{
        \\    const TERMTYPE2 *tp = _nc_fallback2(name);
        \\    const TERMTYPE *result = 0;
        \\    if (tp != 0) {
        \\    static TERMTYPE temp;
        \\    _nc_export_termtype2(&temp, tp);
        \\    result = &temp;
        \\    }
        \\    return result;
        \\}
        \\#endif
        \\
    );
}
