const std = @import("std");

pub fn main(init: std.process.Init) !void {
    // const gpa = init.gpa;
    const io = init.io;
    const args = try init.minimal.args.toSlice(init.arena.allocator());
    const cwd = std.Io.Dir.cwd();

    std.debug.assert(args.len >= 2);
    const outpath = args[1];
    const inpaths = args[2..];

    const outfile = try cwd.createFile(io, outpath, .{});
    defer outfile.close(io);

    var outbuf: [4096]u8 = undefined;
    var output = outfile.writer(io, &outbuf);
    defer output.interface.flush() catch unreachable;
    const writer = &output.interface;

    try writer.print(
        \\/* This file was generated by {s} */
        \\#ifndef PARAMETRIZED_H
        \\#define PARAMETRIZED_H 1
        \\/*
        \\ * parametrized.h --- is a termcap capability parametrized?
        \\ *
        \\ * Note: this file is generated using MKparametrized.sh, do not edit by hand.
        \\ * A value of -1 in the table means suppress both pad and % translations.
        \\ * A value of 0 in the table means do pad but not % translations.
        \\ * A value of 1 in the table means do both pad and % translations.
        \\ */
        \\
        \\static short const parametrized[] = {{
        \\
    , .{@src().file});

    // We detect whether % translations should be done by looking for #[0-9] in the
    // description field.  We presently suppress padding translation only for the
    // XENIX acs_* capabilities.  Maybe someday we'll dedicate a flag field for
    // this, that would be cleaner....

    var entries: usize = 0;

    for (inpaths) |file_path| {
        const fd = try cwd.openFile(io, file_path, .{});
        defer fd.close(io);
        var read_buf: [4096]u8 = undefined;
        var reader = fd.reader(io, &read_buf);

        line: while (try reader.interface.takeDelimiter('\n')) |line| {
            if (line.len == 0) continue;

            inline for (&.{
                "#",
                "capalias",
                "infoalias",
                "userdef",
                "used_by",
            }) |skip_str| {
                if (std.mem.startsWith(u8, line, skip_str)) continue :line;
            }

            var rows = std.mem.tokenizeAny(u8, line, &std.ascii.whitespace);
            const row1 = rows.next() orelse return error.NotEnoughColumns1;
            const row2 = rows.next() orelse return error.NotEnoughColumns2;
            const row3 = rows.next() orelse return error.NotEnoughColumns3;

            if (!std.mem.eql(u8, row3, "str")) continue :line;

            if (std.mem.startsWith(u8, row1, "acs_")) {
                try writer.print("-1,\t/*  {s}  */\n", .{row2});
                entries += 1;
                continue :line;
            }

            if (std.mem.startsWith(u8, row1, "label_format")) {
                try writer.print("-1,\t/*  {s}  */\n", .{row2});
                entries += 1;
                continue :line;
            }

            if (std.mem.find(u8, line, "#")) |hash_pos| {
                if (hash_pos < line.len - 1) {
                    const hash_num = line[hash_pos + 1];
                    switch (hash_num) {
                        '0'...'9' => {
                            try writer.print("1,\t/*  {s}  */\n", .{row2});
                            entries += 1;
                            continue :line;
                        },
                        else => {},
                    }
                }
            }

            try writer.print("0,\t/*  {s}  */\n", .{row2});
            entries += 1;
            continue :line;
        }
    }

    try writer.print("}} /* {d} entries */;\n\n#endif /* PARAMETRIZED_H */\n", .{
        entries,
    });
}
