const std = @import("std");

// MKncurses_def.sh

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    const cwd = std.Io.Dir.cwd();

    std.debug.assert(args.len == 3);
    const inpath = args[1];
    const outpath = args[2];

    const infile = try cwd.readFileAlloc(io, inpath, gpa, .unlimited);
    defer gpa.free(infile);

    const outfile = try cwd.createFile(io, outpath, .{});
    defer outfile.close(io);

    var outbuf: [4096]u8 = undefined;
    var output = outfile.writer(io, &outbuf);
    defer output.interface.flush() catch unreachable;
    const writer = &output.interface;

    try writer.print(
        \\/*
        \\ * This file is generated by {s}
        \\*/
        \\
        \\#ifndef NC_DEFINE_H
        \\#define NC_DEFINE_H 1
        \\
    , .{@src().file});

    var line_iter = std.mem.splitScalar(
        u8,
        infile,
        '\n',
    );
    while (line_iter.next()) |line| {
        if (line.len == 0) {
            try writer.writeAll("\n");
            continue;
        }
        if (std.mem.startsWith(u8, line, "#")) {
            // try writer.writeAll("// ");
            // try writer.writeAll(line);
            // try writer.writeAll("\n");
            continue;
        }
        var field_iter = std.mem.tokenizeAny(
            u8,
            line,
            "\t ",
        );
        var key: []const u8 = "";
        var value: []const u8 = "0";
        var field_num: usize = 0;
        var offset: usize = 0;
        var last_index: usize = 0;
        while (field_iter.next()) |field| : ({
            field_num += 1;
            last_index = field_iter.index;
        }) {
            switch (field_num) {
                0 => {
                    key = field;
                    offset += field.len;
                },
                1 => {
                    value = std.mem.trim(
                        u8,
                        line[last_index..],
                        "\n\t\r ",
                    );
                    break;
                },
                else => unreachable,
            }
        }
        // std.log.debug("key:'{s}', value:'{s}'", .{key, value});
        try writer.writeAll("#ifndef ");
        try writer.writeAll(key);
        try writer.writeAll("\n#define ");
        try writer.writeAll(key);
        try writer.writeAll(" ");
        try writer.writeAll(value);
        try writer.writeAll("\n#endif\n\n");
    }

    try writer.writeAll(
        \\
        \\#endif /* NC_DEFINE_H */
        \\
        \\
    );
}
