const std = @import("std");
const Capability = @import("Capability.zig");

// MKkeys_list.sh translated to zig

pub fn main(init: std.process.Init) !void {
    const gpa = init.gpa;
    const io = init.io;
    const arena = init.arena.allocator();
    const args = try init.minimal.args.toSlice(arena);
    const cwd = std.Io.Dir.cwd();

    std.debug.assert(args.len >= 3);
    const outpath = args[1];
    const inpaths = args[2..];

    var caps: Capability.List = .empty;
    defer caps.deinit(gpa);

    for (inpaths) |inpath| {
        const infile = try cwd.readFileAlloc(io, inpath, arena, .unlimited);
        try caps.parseFile(gpa, infile);
    }
    caps.sortBy_termcap_name();

    const outfile = try cwd.createFile(io, outpath, .{});
    defer outfile.close(io);

    var outbuf: [4096]u8 = undefined;
    var output = outfile.writer(io, &outbuf);
    const writer = &output.interface;

    try writer.print("# These definitions were generated by {s} ", .{@src().file});
    for (inpaths) |ip| {
        try writer.print(" {s}", .{std.fs.path.basename(ip)});
    }
    try writer.writeAll(
        \\
        \\KEY_BREAK
        \\KEY_SRESET
        \\KEY_RESET
        \\
    );

    for (caps.array.items) |cap| {
        if (std.mem.startsWith(u8, cap.termcap_name, "KEY_")) {
            try writer.print("{s}\t{s}\n", .{ cap.termcap_name, cap.terminfo_var });
        }
    }

    try writer.flush();
}
